### ISSUE TITLE
Doesn't this read sensitive information too like passwords and configs typed?

### ISSUE THREAD

**Issue by nikitavoloboev** [wbinglee/zsh-wakatime#16]

**Comment by alanhamlett** [comment]
No, it only sends the program name being run in zsh not the arguments to that program.

**Comment by wbinglee** [comment]
Check the code here:  https://github.com/wbinglee/zsh-wakatime/blob/master/zsh-wakatime.plugin.zsh#L18
```
 # only command without arguments to avoid senstive information
echo "$history[$((HISTCMD-1))]" | cut -d ' ' -f1
```

It only send out command name,  if you run command say "mysql --pass mypassword", only "mysql" will be sent to wakatime.

**Comment by untoreh** [comment]
in case the command is a file path wouldn't it be better to parse only the basename?
